# Generated by Django 6.0 on 2026-01-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.IntegerField()),
                ('city_size', models.CharField(max_length=15)),
                ('city_type', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='TourismStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('nights_spent', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
            ],
            options={
                'db_table': 'tourism_stat',
                'unique_together': {('country', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_receiver.city')),
            ],
            options={
                'db_table': 'weather_data',
                'unique_together': {('city', 'date')},
            },
        ),
    ]
