# Generated by Django 6.0 on 2026-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismstat',
            name='nights_spent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tourismstat',
            name='occupancy_rate',
            field=models.FloatField(null=True),
        ),
    ]
