# Generated by Django 6.0 on 2026-01-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0002_alter_tourismstat_nights_spent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
