# Generated by Django 6.0 on 2026-01-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0003_delete_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('period', models.IntegerField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_receiver.city')),
            ],
            options={
                'db_table': 'weather_data',
                'unique_together': {('city', 'year', 'period')},
            },
        ),
    ]
