# Generated by Django 6.0 on 2026-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0004_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
