# Generated by Django 6.0 on 2026-01-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0005_city_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
