# Generated by Django 6.0 on 2026-01-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0006_city_country_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_ru',
        ),
    ]
