# Generated by Django 6.0 on 2026-01-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0007_remove_city_country_ru'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('city', 'period')},
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['city', 'period'], name='weather_dat_city_id_e0be87_idx'),
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='year',
        ),
    ]
