# Generated by Django 6.0 on 2026-01-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0008_alter_weatherdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='weatherdata',
            name='weather_dat_city_id_e0be87_idx',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
