# Generated by Django 6.0 on 2026-01-14 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0009_alter_weatherdata_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('mean_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('min_relative_humidity', models.IntegerField()),
                ('mean_relative_humidity', models.IntegerField()),
                ('daylight_duration', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_receiver.city')),
            ],
            options={
                'db_table': 'weather_data',
                'indexes': [models.Index(fields=['city', 'period'], name='weather_dat_city_id_e0be87_idx')],
                'unique_together': {('city', 'period')},
            },
        ),
    ]
