# Generated by Django 6.0 on 2026-01-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0010_weatherdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourismstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tourismstat',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='tourismstat',
            name='date',
        ),
    ]
