# Generated by Django 6.0 on 2026-01-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0011_alter_tourismstat_unique_together_tourismstat_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourismstat',
            unique_together={('country', 'month')},
        ),
    ]
