# Generated by Django 6.0 on 2026-01-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0012_alter_tourismstat_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismstat',
            name='nights_spent',
        ),
    ]
