# Generated by Django 6.0 on 2026-01-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_receiver', '0013_remove_tourismstat_nights_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_type',
        ),
    ]
